// /*
//  * This is sample code generated by rpcgen.
//  * These are only templates and you can use them
//  * as a guideline for developing your own functions.
//  */

// #include "date.h"


// void
// date_prog_1(char *host)
// {
// 	CLIENT *clnt;
// 	long  *result_1;
// 	char *bin_date_1_arg;
// 	char * *result_2;
// 	long  str_date_1_arg;

// #ifndef	DEBUG
// 	clnt = clnt_create (host, DATE_PROG, DATE_VERS, "udp");
// 	if (clnt == NULL) {
// 		clnt_pcreateerror (host);
// 		exit (1);
// 	}
// #endif	/* DEBUG */

// 	result_1 = bin_date_1((void*)&bin_date_1_arg, clnt);
// 	if (result_1 == (long *) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// 	result_2 = str_date_1(&str_date_1_arg, clnt);
// 	if (result_2 == (char **) NULL) {
// 		clnt_perror (clnt, "call failed");
// 	}
// #ifndef	DEBUG
// 	clnt_destroy (clnt);
// #endif	 /* DEBUG */
// }


// int
// main (int argc, char *argv[])
// {
// 	char *host;

// 	if (argc < 2) {
// 		printf ("usage: %s server_host\n", argv[0]);
// 		exit (1);
// 	}
// 	host = argv[1];
// 	date_prog_1 (host);
// exit (0);
// }


/* rdate.c - client program for remote date service. */
#include <stdio.h>
#include <rpc/rpc.h> /* standard RPC include file */
#include "date.h" /* this file is generated by rpcgen */
main(argc, argv)
int argc;
char *argv[];
{
 CLIENT *cl; /* RPC handle */
 char *server;
 long *lresult; /* return value from bin_date_1() */
 char **sresult; /* return value from str_date_1() */
 if (argc != 2) { fprintf(stderr, "usage: %s hostname\n", argv[0]); exit(1); }
 server = argv[1];
/*Create the client "handle." */
 if ( (cl = clnt_create(server, DATE_PROG, DATE_VERS, "udp")) == NULL) {
 /* Couldn't establish connection with server. */
 clnt_pcreateerror(server);
 exit(2);
 }
/* First call the remote procedure "bin_date". */
 if ( (lresult = bin_date_1(NULL, cl)) == NULL) {
 clnt_perror(cl, server);
 exit(3);
 }
 printf("time on host %s = %ld\n", server, *lresult);
/* Now call the remote procedure "str_date". */
 if ( (sresult = str_date_1(lresult, cl)) == NULL) {
 clnt_perror(cl, server);
 exit(4);
 }
 printf("time on host %s = %s", server, *sresult);
 clnt_destroy(cl); /* done with the handle */
 exit(0);
} 